# Generated by Django 2.1.2 on 2018-11-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_auto_20181119_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='distance_from_location',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='messenger.Category'),
        ),
    ]
